---
- name: check httpd,apache2 and enable
  hosts: all
  tasks: 
    - name: check httpd,apache2 and enable it
      package_facts:
      register: packages

    - name: restart httpd and apache2 if installed
      service:
        name: "{{ 'httpd' if 'httpd' in packages.ansible_facts.packages else 'apache2' }}"
        state: started
        enabled: yes

      when: " 'httpd' in packages.ansible_facts.packages or 'apache2' in packages.ansible_facts.packages "
...


